const nationOptions = {
  data() {
    return {
      nations: [
        { label: "汉族", value: "汉族" },
        { label: "蒙古族", value: "蒙古族" },
        { label: "回族", value: "回族" },
        { label: "藏族", value: "藏族" },
        { label: "维吾尔族", value: "维吾尔族" },
        { label: "苗族", value: "苗族" },
        { label: "彝族", value: "彝族" },
        { label: "壮族", value: "壮族" },
        { label: "布依族", value: "布依族 " },
        { label: "朝鲜族", value: "朝鲜族" },
        { label: "满族", value: "满族" },
        { label: "侗族", value: "侗族" },
        { label: "瑶族", value: "瑶族" },
        { label: "白族", value: "白族" },
        { label: "土家族", value: "土家族" },
        { label: "哈尼族", value: "哈尼族" },
        { label: "哈萨克族", value: "哈萨克族" },
        { label: "傣族", value: "傣族" },
        { label: "黎族", value: "黎族" },
        { label: "傈僳族", value: "傈僳族" },
        { label: "佤族", value: "佤族" },
        { label: "畲族", value: "畲族" },
        { label: "高山族", value: "高山族" },
        { label: "拉祜族", value: "拉祜族" },
        { label: "水族", value: "水族" },
        { label: "东乡族", value: "东乡族" },
        { label: "纳西族", value: "纳西族" },
        { label: "景颇族", value: "景颇族" },
        { label: "柯尔克孜族", value: "柯尔克孜族" },
        { label: "土族", value: "土族" },
        { label: "达斡尔族", value: "达斡尔族" },
        { label: "仫佬族", value: "仫佬族" },
        { label: "羌族", value: "羌族" },
        { label: "布朗族", value: "布朗族" },
        { label: "撒拉族", value: "撒拉族" },
        { label: "毛南族", value: "毛南族" },
        { label: "仡佬族", value: "仡佬族" },
        { label: "锡伯族", value: "锡伯族" },
        { label: "阿昌族", value: "阿昌族" },
        { label: "普米族", value: "普米族" },
        { label: "塔吉克族", value: "塔吉克族" },
        { label: "怒族", value: "怒族" },
        { label: "乌孜别克族", value: "乌孜别克族" },
        { label: "俄罗斯族", value: "俄罗斯族" },
        { label: "鄂温克族", value: "鄂温克族" },
        { label: "德昂族", value: "德昂族" },
        { label: "保安族", value: "保安族" },
        { label: "裕固族", value: "裕固族" },
        { label: "京族", value: "京族" },
        { label: "塔塔尔族", value: "塔塔尔族" },
        { label: "独龙族", value: "独龙族" },
        { label: "鄂伦春族", value: "鄂伦春族" },
        { label: "赫哲族", value: "赫哲族" },
        { label: "门巴族", value: "门巴族" },
        { label: "珞巴族", value: "珞巴族" },
        { label: "基诺族", value: "基诺族" },
      ],
      departmentOptions: [
        {
          label: "石油与天然气工程学院",
          value: "石油与天然气工程学院",
          majorOptions: [
            { label: "石油工程", value: "石油工程" },
            { label: "油气储运工程", value: "油气储运工程" },
          ],
        },
        {
          label: "计算机科学学院",
          value: "计算机科学学院",
          majorOptions: [
            { label: "网络工程", value: "网络工程" },
            { label: "软件工程", value: "软件工程" },
            { label: "物联网工程", value: "物联网工程" },
            { label: "网络空间安全", value: "网络空间安全" },
          ],
        },
        {
          label: "化学化工学院",
          value: "化学化工学院",
          majorOptions: [
            { label: "应用化学", value: "应用化学" },
            { label: "环境工程", value: "环境工程专业" },
            { label: "安全工程", value: "安全工程" },
          ],
        },
        {
          label: "法学院",
          value: "法学院",
          majorOptions: [
            { label: "法学", value: "法学" },
            { label: "社会学", value: "社会学" },
          ],
        },
      ],
    };
  },
};

export default nationOptions;
