const nationOptions = {
  data() {
    return {
      nations: [
        { label: "汉族", value: "Han" }, 
        { label: "蒙古族", value: "Mongolian"},
        { label: "回族", value: "Hui" },  
        { label: "藏族", value: "Tibetan" },  
        { label: "维吾尔族", value: "Uighur" },  
        { label: "苗族", value: "Miao" },  
        { label: "彝族", value: "Yi" },  
        { label: "壮族", value: "Zhuang" },  
        { label: "布依族", value: "Buyi " }, 
        { label: "朝鲜族", value: "Korean" },  
        { label: "满族", value: "Manchu" },  
        { label: "侗族", value: "Dong" },  
        { label: "瑶族", value: "Yao" },
        { label: "白族",value: "Bai" },
        { label: "土家族", value: "Tujia" },
        { label: "哈尼族", value: "Hani" },
        { label: "哈萨克族", value: "Kazakh" },
        { label: "傣族", value: "Dai" },
        { label: "黎族", value: "Li" },
        { label: "傈僳族", value: "Lisu" },
        { label: "佤族", value: "WA" },
        { label: "畲族", value: "she" },
        { label: "高山族", value: "gaoshanzu" },
        { label: "拉祜族", value: "Lahu" },
        { label: "水族", value: "Aquarium" },
        { label: "东乡族", value: "Dongxiang" },
        { label: "纳西族", value: "Naxi" },
        { label: "景颇族", value: "Jingpo nationality" },
        { label: "柯尔克孜族", value: "Kirgiz" },
        { label: "土族", value: "Tu" },
        { label: "达斡尔族", value: "Daur" },
        { label: "仫佬族", value: "Mulao Nationality" },
        { label: "羌族", value: "Qiang" },
        { label: "布朗族", value: "Bulang family" },
        { label: "撒拉族", value: "Salar" },
        { label: "毛南族", value: "Maonan" },
        { label: "仡佬族", value: "Gelao" },
        { label: "锡伯族", value: "Xibe" },
        { label: "阿昌族", value: "Achang" },
        { label: "普米族", value: "Pumi" },
        { label: "塔吉克族", value: "Tajik" },
        { label: "怒族", value: "Nu clan" },
        { label: "乌孜别克族", value: "Uzbek" },
        { label: "俄罗斯族", value: "Russians" },
        { label: "鄂温克族", value: "Ewenki" },
        { label: "德昂族", value: "De'ang clan" },
        { label: "保安族", value: "Bao'an family" },
        { label: "裕固族", value: "Yugur" },
        { label: "京族", value: "Jingzu" },
        { label: "塔塔尔族", value: "Tatar family" },
        { label: "独龙族", value: "Dulong" },
        { label: "鄂伦春族", value: "Oroqen" },
        { label: "赫哲族", value: "Hezhe" },
        { label: "门巴族", value: "Menba" },
        { label: "珞巴族",  value: "Lhoba" },
        { label: "基诺族", value: "Jinuo family" }, 
      ]
    }
  }
}

export default nationOptions